### ISSUE TITLE
Error creating stackit_dns_record_set: "... produced an unexpected new value."

### ISSUE THREAD

**Issue by jebreuer** [stackitcloud/terraform-provider-stackit#246]
I'm trying to create a stackit_dns_record_set. This is the error I face:
![Bildschirmfoto 2024-02-06 um 14 24 25](https://github.com/stackitcloud/terraform-provider-stackit/assets/10113383/e90b8061-edb2-41e2-9b68-12a912a42bd3)

Provider Versions tested:

- 0.9.2
- 0.9.1

Any help is highly appreciated.

Thank you!
Jens

**Comment by vicentepinto98** [comment]
Hello @jebreuer,
The issue is that the DNS API returns the FQDN based on the provided record-set name and we are setting it back to that field, which causes this inconsistent result. This is a known issue and we plan to fix it soon (until end of the month). 

In the meantime, as a workaround, you can set the record-set name to the FQDN (the second value shown in the error message). If I'm not mistaken, you just need to add a `.`  at the end of your record-set name.

Let me know if this fixes the error

**Comment by jebreuer** [comment]
Hi @vicentepinto98!

The workaround is acceptable from my perspective.

Thank you!

**Comment by DiogoFerrao** [comment]
This bug was fixed in the newest Release [v0.15.0](https://registry.terraform.io/providers/stackitcloud/stackit/0.15.0)
